---

- name: Install Java 7 JDK
  apt: name=openjdk-7-jdk state=present update_cache=yes

- name: Install Tomcat 7
  apt: name=tomcat7 state=present

- name: Start Tomcat
  service: name=tomcat7 state=started enabled=yes